index:
    path:     /
    defaults: { _controller: AppBundle:Base:index }
paginate:
    path:     /paginate
    defaults: { _controller: AppBundle:Base:paginate }
json:
    path:     /json
    defaults: { _controller: AppBundle:Base:json}
add:
    path:     /add/{name}/{author}/{genre}/{year}
    defaults: { _controller: AppBundle:Base:add}
